In [3]:
import numpy as np

# 创建一些示例数据
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([[1, 2, 3], [4, 5, 6]])

# 将数据保存到 NPZ 文件中
np.savez('/data.npz', array1=array1, array2=array2)

# 从 NPZ 文件中读取数据
data = np.load('data.npz')

# 获取保存的数组
loaded_array1 = data['array1']
loaded_array2 = data['array2']

# 打印加载的数组
print("Loaded Array 1:")
print(loaded_array1)

print("Loaded Array 2:")
print(loaded_array2)

# 关闭文件
data.close()


Loaded Array 1:
[1 2 3 4 5]
Loaded Array 2:
[[1 2 3]
 [4 5 6]]
